# Sample application properties
server.port=8080
spring.application.name=maven-application-labfat
logging.level.root=INFO

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=password

# Other configurations
app.feature.enable=true
app.timeout=30